version: '2'

services:
  mongodb:
    image: mongo:3.4
    ports:
      - "27017:27017"
    networks:
      mongo_net:
        ipv4_address: 172.16.0.1
    command: mongod --bind_ip 127.0.0.1,172.16.0.1
    
  mtsw:
    build: .
    networks:
      mongo_net:
    depends_on:
        - mongodb
    volumes:
        - ./notebooks/:/home/jovyan/notebooks:rw
    ports:
        - 8888:8888

networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.254
